In [25]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np
import matplotlib.pyplot as plt

#1 Procesamiento de datos

time_series = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("time_series: ",time_series)
train_size = int(len(time_series)* 0.6) #tramano del conjunto de entrenamiento
train_data, test_data  = time_series[:train_size], time_series[train_size:]
print("train_data",train_data)
print("test_data",test_data)



time_series:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
train_data [1 2 3 4 5 6 7 8 9]
test_data [10 11 12 13 14 15]


In [26]:
#Paso 2. Preparacion de datos para LSTM (ejemplo basico)
#trasformamos nuestros datos en secuencias

def create_dataset(data, seq_length):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i + seq_length])
        y.append(data[i + seq_length])
    return np.array(X), np.array(y)

#definimos el numero de pasos de tiempo para la seie temporal

seq_legth = 4
#cremos conjuntos de entrenamiento y prueba en formato 3D
X_train, y_train = create_dataset(train_data, seq_legth)
X_test, y_test =  create_dataset(test_data, seq_legth)

#cremos conjuntos de entrenamiento y prueba en formato 3D
print("conjunto de secuencias de entrenamiento: \n",X_train)
print("Etiquetas de entrenamiento: \n",y_train)
print("conjunto de secuencias de prueba: \n",X_test)
print("Etiquetas de prueba: \n",y_test)



conjunto de secuencias de entrenamiento: 
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
Etiquetas de entrenamiento: 
 [5 6 7 8 9]
conjunto de secuencias de prueba: 
 [[10 11 12 13]
 [11 12 13 14]]
Etiquetas de prueba: 
 [14 15]


In [27]:
#Paso 3: construccion del modelo

model = Sequential()
model.add(LSTM(16, activation='relu', input_shape=(seq_legth,1)))
model.add(Dense(1))


#4 compilacion del modelo
model.compile(optimizer='adam', loss='mse')

#Paso 5: entreanmiento del modelo
model.fit(X_train, y_train, epochs=500)





Epoch 1/500


c:\Users\julig\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 40.6165
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 40.3253
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 40.0300
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 39.7305
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 39.4266
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 39.1182
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 38.8049
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 38.4865
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 38.1628
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 37.8335
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 37.4981
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 37.1564
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 36.8081
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 36.4527
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 36.0900
Epoch 16/500
1/1 ━

In [28]:
#Paso 6: evalucion del modelo
evaluacion = model.evaluate(X_test, y_test)
print(evaluacion)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step - loss: 0.7381
0.738102912902832


In [29]:
print("X_test \n",X_test)
print("y_test: \n", y_test)
y_pred = model.predict(X_test)
print("y_pred: \n", y_pred)


X_test 
 [[10 11 12 13]
 [11 12 13 14]]
y_test: 
 [14 15]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step
y_pred: 
 [[13.175443]
 [14.107637]]


1. la biblioteca para im plementar LSTM es Sequential
2. el proposito del paso 1 es: 
    definir la serie de tiempo 
    definir el tamano del conjunto de datos de entrenamiento 60% => 9 datos
    definir los datos de entrenamiento y pruebas
3. la funcion create_dataset 
    en general convierte una serie temporal en un con junto de datos que puede ser nutilizado para entrenar modelos de prediccion
    Entrada:  1 recibe un serie temporal 
              2. la longitud dfe secuenicas de entrada que se utilizaran para predecir el siguiente valor en la serie temporal
    salida: 
              X:  un array donde Ccada elemento es un secuencia de  longitud seq_lenthg tomada de data
              y: un array de valores que contiene el siguiente valor en la serie temporal inmediatamnete despues de cada secuencia en x
4. seq_legth representa cuantos pasos de tiempo anteiores (o cuantos valores) se toman como entrada para predecir el siguiente valor o una secuencia futura
   ejemplo: si quiwero predecir las ventas de un producto cada 30 minutos y seq_lenght =4 estoy diciendo que utilizare los ultimos 4 intervalos de 30 minutos (2 horas) como entyrada para predecir ventas del proximo intervalo de 30 minutos
5. es necesario trasnformar los datos en secuencias en el paso 2 porque las secuencias permiten al modelo considerar los patrones recurrentres pasados, poder aprenderlos y realizar predicciones a futuro 

    
              